export const ADDED_TO_CART = 'ADDED_TO_CART';
export const REMOVED_FROM_CART = 'REMOVED_FROM_CART';
export const AMOUNT_CHANGED = 'AMOUNT_CHANGED';
export const INPUT_CUSTOMER_DATA = "INPUT_CUSTOMER_DATA";